### ISSUE TITLE
Embedded graphics

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#14]
[Data Story.pptx](https://github.com/axismaps/ridership/files/2715762/Data.Story.pptx)

**Comment by bwellington** [comment]
embed parameters:

dropdownsOn
compared (ta1|ta2|ta3)
embed (atlas, msaAtlas, sparkLines, sidebarSparklines, sidebarPCP, histogram)
distanceFilter (0.25, 0.5, 1)
indicator
msa
nationalDataView (ta, msa)
scale (national, msa)
years (e.g. 2005|2010)

**Comment by davidheyman** [comment]
This looks great. Just one thing I want to clarify on the indicator property:

1. For maps, the indicator property can only have 1 option and defines which indicator is mapped.
2. For the sparkles and PCP, the indicator property can have multiple options and will define which indicators are shown in the chart. For example, sending the sparkline `rail|bus|upt|` will show 3 sparklines, one for each indicator. For the PCP, you can send those same three variables and get a PCP with 3 rows.

**Comment by bwellington** [comment]
Ah interesting, got it

**Comment by davidheyman** [comment]
Final task is to create an embedded page based on their data story.

**Comment by davidheyman** [comment]
Needs documentation as well

**Comment by davidheyman** [comment]
> embed parameters:
> 
> dropdownsOn
> compared (ta1|ta2|ta3)
> embed (atlas, msaAtlas, sparkLines, sidebarSparklines, sidebarPCP, histogram)
> distanceFilter (0.25, 0.5, 1)
> indicator
> msa
> nationalDataView (ta, msa)
> scale (national, msa)
> years (e.g. 2005|2010)

@awoodruff Can you take a look at these and let me know which ones are in (beyond what's in story.html)? We may have to add the ones that never got built.

**Comment by davidheyman** [comment]
@awoodruff Can we also have an 'expanded' property that sets the sparklines to start expanded? It's OK if this only works when there is just 1 indicator listed in the 'indicator' parameter.

**Comment by davidheyman** [comment]
@awoodruff I've got another one for you:

Can we specify a 'selected' indicator like it appears here?

![2019-03-13_10-50-41](https://user-images.githubusercontent.com/791434/54273512-f4b14e80-457d-11e9-8965-1ef266048cbf.png)

**Comment by davidheyman** [comment]
Let's also add support for a starting bounding box for the MSA map. I'm always confused about the order of those things but it should be another pipe-separated array.

**Comment by awoodruff** [comment]
@davidheyman the new params are:
`selected=[indicator]`
`bounds=west|south|east|north`
