### ISSUE TITLE
Data probes on sparklines with multiple lines

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#16]
Two ways to handle this:

1. Have the probe show all values
2. Probe individual lines one-at-a time

I don’t have a strong preference either way.

**Comment by awoodruff** [comment]
Lists out all values now. This could get out of hand if someone compares like 50 agencies, but hopefully they won't!

![screen shot 2019-01-02 at 12 20 38 pm](https://user-images.githubusercontent.com/3533462/50603549-e01f4e80-0e88-11e9-8e2a-b48247a67466.png)
