### ISSUE TITLE
Census tract data probe

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#27]

**Comment by bcsheesley** [comment]
![screen shot 2019-01-14 at 10 30 15 am](https://user-images.githubusercontent.com/4501388/51125927-73407880-17e7-11e9-9898-a4f8a22e13c2.png)

**Comment by bcsheesley** [comment]
Highlighting should be linked to the histogram as well. I.e., mousing over a bar would add a black outline to all the associated tracts on the map and mousing over a tract would highlight the associated bar.

**Comment by bwellington** [comment]
Updated (I accidentally referenced the wrong issue in the commits). Do we need anything that indicates that the number is % change for the selected years? Also, is the width OK as it is (fixed)?

**Comment by bwellington** [comment]
Updated. Should non-highlighted tracts fade back, like we do with agencies in the national-scale map?

**Comment by bcsheesley** [comment]
Nah, let's not worry about that for now. I really like how it helps group the circles within an MSA at the  nation-scale, but probably not as important here.
