### ISSUE TITLE
Circle packing when map is zoomed

### ISSUE THREAD

**Issue by awoodruff** [axismaps/ridership#3]
Flagging this so I don't forget.
If you first zoom in on the national map, then switch between MSA and TA mode, circle symbols are redrawn with their layout presumably based on the current scale. If you then zoom out, the circles will overlap.

**Comment by bwellington** [comment]
Yeah, the circle clustering needs to be calculated when zoomed out all the way. It probably makes sense to just show/hide the cluster TA layer, instead of redrawing and recalculating.
