### ISSUE TITLE
Crazy outliers in median income data

### ISSUE THREAD

**Issue by awoodruff** [axismaps/ridership#34]
In some MSAs (Boston and NYC for example) when the starting year is 2010, there's some wacky negative outlier(s) in Median Income that kind of wrecks the histogram. Perhaps bad data, or perhaps the % change calculation not accounting for a null or something?

**Comment by davidheyman** [comment]
I've found and removed the crazy outliers but the histogram still doesn't draw for 2010 - 2015 in New York or LA. I don't think it's a cache issue on my end...
