### ISSUE TITLE
Mobile page should not scroll

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#37]
![img_d856478091d2-1](https://user-images.githubusercontent.com/791434/52590972-96883300-2e3a-11e9-8b56-f999b0e11961.jpeg)

**Comment by davidheyman** [comment]
Desktop shouldn't scroll either!

**Comment by bwellington** [comment]
Could you give an example of when desktop inappropriately scrolls? I assume we want it to scroll if window dimensions are less than the minimum map dimensions?

**Comment by davidheyman** [comment]
Looks like it's Safari-only:

![2019-03-04_09-52-55](https://user-images.githubusercontent.com/791434/53725176-5d544900-3e63-11e9-9645-c8dd2b598666.png)
