### ISSUE TITLE
Default years for national / msa views

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#39]
https://www.notion.so/axismaps/Mobile-iPhone-Desktop-possible-to-set-the-default-to-the-full-range-of-data-for-the-National-dd0ae1967e7e48399095c00d421ffcde

**Comment by awoodruff** [comment]
I think maybe this should reset to the full year range any time you switch between national and MSA? I didn't quite figure out where/how to do that. At the moment it will only change if you were looking at a range outside 2010–2016 when you zoom to MSA.
