### ISSUE TITLE
Update indicator names, units, rounding, format, and order

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#4]
[TC_Viz_Indicators.xlsx](https://github.com/axismaps/ridership/files/2686729/TC_Viz_Indicators.xlsx)

[Notion](https://www.notion.so/axismaps/Updated-indicator-names-units-rounding-format-and-order-in-Viz_indicators-excel-spreadsheet-1b6412056a7d49f2a4f2343352642d30)

**Comment by awoodruff** [comment]
These are all in, including formats and units for census indicators, though those do not yet have any place to be displayed.

Not certain if things like "(mph)" from the spreadsheet are actually intended to appear in the indicator names—I've left them out, but @davidheyman let me know if they should be added.
