### ISSUE TITLE
Truncate indicator names and years with an ellipsis instead of wrapping

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#44]
https://www.notion.so/axismaps/Truncate-indicators-in-the-dropdown-as-needed-to-prevent-wrapping-at-the-min-width-b3194ecdf7644565973919fd176fb270

**Comment by davidheyman** [comment]
Related to this, set a minimum page width of 1024px or 1280px and scroll the whole page if it is narrower than that.

https://www.notion.so/axismaps/Set-minimum-page-width-d91d065c1e274666b76838c7d5ec975b

**Comment by awoodruff** [comment]
87a95a97d84eb96f8fae39eaa295e5222403df74
