### ISSUE TITLE
Add a legend in MSA zoom for stops, bus routes, and rail route symbology

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#45]
Design is here -> https://www.notion.so/axismaps/Add-a-legend-in-MSA-zoom-for-stops-bus-routes-and-rail-route-symbology-fef3e10c07f44f59a8d25ee3b43999c4

**Comment by bcsheesley** [comment]
@bwellington quick Legend update:
Add a straight diagonal line to the legend to indicate express bus route.

Here's the layout and PNG swatch for "Express Bus (by agency)":

![screen_shot_2019-02-22_at_11_06_31_am](https://user-images.githubusercontent.com/4501388/53260665-a7853f80-3697-11e9-9c2b-34f909bc2faa.png)
![bus-express](https://user-images.githubusercontent.com/4501388/53260668-aa803000-3697-11e9-9826-c0b69a2d7ea6.png)
