### ISSUE TITLE
Cap histogram bins at +/- 300%

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#47]
The largest / smallest histogram bin should be +/- 300% and include all values above / below that

https://www.notion.so/axismaps/Currently-the-histogram-for-census-tracts-in-the-MSA-zoom-puts-outliers-like-1000-into-separate-9decb7308e94498ba81f843a4fc44f43

**Comment by bwellington** [comment]
Updated. There are now -100% -> -95% and > 300% bins. The histogram bars also are always increments of either 5 or 10, so color breaks never happen within a bar (so bar colors always match with map colors). Unfortunately, somewhere along the way this seems to have messed up the mobile histogram, so I need to fix that now.
