### ISSUE TITLE
Statewide gas is calculated incorrectly when it includes 2017

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#50]
There are no values for 2017 so these should all be NA

https://www.notion.so/axismaps/Gas-prices-difference-in-how-change-from-any-year-2017-is-calculated-in-transit-agency-vs-msa-on-f265bf61a3f5469a8d81fe0e51fc9708

**Comment by awoodruff** [comment]
Got these showing NA correctly, but leaving this open for the moment because it would be good to do something about this histogram in a case like this, like maybe draw some axis lines and show a big "N/A" label or something. As is, it's just a big blank space if there's no data to show.

**Comment by davidheyman** [comment]
If that’s going to be a pain, a legitimate solution would be changing the year in the selection if all the values are NA.

**Comment by awoodruff** [comment]
Just to show something in place of the histogram (which it does now) is much easier, but let me know if it really ought to do year switching instead.

**Comment by davidheyman** [comment]
We also need a solution for this on the PCP. Options in order of preference are:

1. Break the line so it doesn't go through the indicator with no data
2. Use the next available data year
3. Use a value of 0 instead of -100
