### ISSUE TITLE
Visually differentiate agencies and MSAs in sparkline

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#61]
- Color lines differently and add legend with filter controls
- Display information and percent change and use linear scale for y-axis

**Comment by awoodruff** [comment]
Multiple gray lines in these charts is only a thing in "compare mode" on the national map, I believe—any problem if we limit the number of compared agencies/MSAs to something reasonable for unique colors? (Maybe 10?)

**Comment by davidheyman** [comment]
Yeah. Limit it to 10. If that's an issue, we'll just have to loop back through and reuse the colors.
