### ISSUE TITLE
Display regional values for demographic indicators

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#62]
- Add a flag to the histogram indicating the MSA value for the selected indicator

**Comment by awoodruff** [comment]
@davidheyman do you have workflows set up for census data that can easily be modified to get values for MSAs? I believe we only have demographics by tract now. MSA data could either be added as columns in the existing `msa` table or else in a new table.

**Comment by davidheyman** [comment]
This is going to take some work on my end before it is ready. I'll need to update the data scripts to download and process the MSA data alongside the tract data. 

Are there any `SELECT * FROM msa` queries on the MSA table that might get messed up if the data goes into that table?

**Comment by awoodruff** [comment]
There is a one-time `SELECT * FROM msa` query to get centroids and names and such, but if this data would just be going into additional columns on that table it shouldn't hurt anything.

**Comment by davidheyman** [comment]
This is ready on the msa-data branch. The MSA census data is in the census_msa table on CARTO.

**Comment by awoodruff** [comment]
This is done in the `no-data` branch because it copies some new methods there in case of missing years. The flag label is formatted as "MSA name: value"

**Comment by awoodruff** [comment]
Merged in c234d9a4e38abf242f9d0185222639940011aee4

**Comment by davidheyman** [comment]
These have gone missing. Is it a problem with the data update?

**Comment by awoodruff** [comment]
Should be back now, in one of the recent (re)merges
