### ISSUE TITLE
Update tract filter to only utilize stops from active TAs

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#66]
- Update data to list tract distance from each TAs closest stop
- Tract filter will query tracts by distance and active TAs

**Comment by davidheyman** [comment]
The data for this is ready to go in d2432c1c

Each tract now has attributes called `i250`, `i500` and `i1000` for the distance from the high frequency stop. Each one of these attributes contains an array of taid's that serve the stops within that buffer. A taid of `9999` means that I couldn't match by name and should only display when **all** TAs are active.

**Comment by awoodruff** [comment]
@davidheyman I made a separate `ta-filter` branch for the front-end bit, because at first I was struggling with some data updates. Anyway I this is ready in there now, but you may want to confirm that things look right.

**Comment by davidheyman** [comment]
Some reported bugs from this feature:

1. Denver, where filtering for either transit agency & tracts near frequent transit generates no data, but filtering for both transit agencies shows there are many tracts near frequent transit in the area
2. See Philadelphia, where filtering for SEPTA, SEPTA & PATCO, & PATCO yields the same result, which looks like the tracts served by frequent PATCO service.
3. Data issue: Chicago frequency data appears to be off, with most of the area’s frequent service not showing up. Last year there was in issue showing frequent rail service - is it possible this carried over to the new version? Here’s a map I put together using the TransitLand shapefiles.

These might be all issues with name matching...

**Comment by awoodruff** [comment]
Yeah maybe name matching issues? At least on the first two... 

1. Denver only has the `9999` values, so they only appear if _both_ agencies are active (though they almost certainly all belong to one).

2. In Philadelphia it looks like only PATCO matched (the others got `9999`'d), but there are also tracts matching NJ Transit, which isn't included for this city. This might result in some tracts showing up in places where there don't appear the be high frequency stops, but I'm not sure.

3. No high frequency stops for CTA appear on the map, though they presumably exist. I remember seeing some special rule for Chicago in the Mapbox style or something, probably related to this? I forget what it is, or if it still exists; will have to look into it.
