### ISSUE TITLE
Allow selection of new indicators to scale map symbols

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#67]
- Add a new dropdown menu with additional transit indicators (e.g., bus / rail ridership)
- Update map point scaling to use the selected indicator

**Comment by davidheyman** [comment]
Fixed in #74

**Comment by awoodruff** [comment]
Oops, the map legend needs to update, too.

**Comment by awoodruff** [comment]
This got wrecked in the `no-data` branch merge c234d9a4e38abf242f9d0185222639940011aee4
