### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#75]
The webpack url-loader doesn't like having relative URLs. I started to fix it with e406712 but there are still problems.

**Comment by awoodruff** [comment]
Did this begin to occur along with some other necessary change? Things seem to build okay for me if I simply revert e406712ef40a03474023e5f9cb1a627a0f4b4b09

**Comment by davidheyman** [comment]
Yeah. The change was required to get it to run from a directory that isn't the root.

**Comment by davidheyman** [comment]
I should also mention that I can get it to build, it just has missing images. If you're having build issues, try installing the dependencies again.
