### ISSUE TITLE
Latest data not displaying on regional map

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#86]

**Comment by awoodruff** [comment]
May be fixed after this merge -> 91817caa48900202e48abd5e72150df2d5899093

**Comment by awoodruff** [comment]
Actually, missed the word "indicator" in the title here; the real fix here would be in dca2b79.

**Comment by awoodruff** [comment]
^ and by "indicator" I mean "regional". There are like 5 words in this project and they're starting to blur together.
