### ISSUE TITLE
Select / de-select all agencies

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#87]
In regional view, add a button on top that quickly allows the user to select / de-select all agencies

**Comment by awoodruff** [comment]
I've done this as a button that says "show all agencies" or "hide all agencies". If _any_ boxes are unchecked, the button will switch them all on. Only if _all_ boxes are checked does the button turn them all off. I think that's how this kind of group-level toggle usually works, but I could be wrong.
