### ISSUE TITLE
Image export

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#9]

**Comment by awoodruff** [comment]
This is basically functional but could probably use some @bcsheesley refinement. Some examples are attached here. It strives for a screenshot-esque image of map, sidebar, and histogram. One big questionable thing is that the sidebar can easily be much taller than the map/histogram so the whole image looks a little silly, but maybe that isn't important?

Easy things to adjust:

- margins/padding
- text styles outside of svg elements (i.e. not most chart axes or the map legend)
- general arrangement of the main components

Not so feasible things to adjust:

- anything within in the graphics themselves (fill and stroke, etc., unless it also changes in the interactive)
- extents and scales — whole images can be scaled up or down but I can't, for example, extend the map to fill in blank space

![national](https://user-images.githubusercontent.com/3533462/50602867-9cc3e080-0e86-11e9-95ee-0eb6eb68c9b3.png)

![msa](https://user-images.githubusercontent.com/3533462/50602876-9fbed100-0e86-11e9-982d-c41c8cc58e37.png)

![compare_pcp](https://user-images.githubusercontent.com/3533462/50602881-a3525800-0e86-11e9-9c6a-b69e28b74014.png)

![sparkline_expanded](https://user-images.githubusercontent.com/3533462/50603260-e8c35500-0e87-11e9-80c9-c75785cef82e.png)

**Comment by davidheyman** [comment]
Closing this as complete.

@bcsheesley remember to look at this during your review!
